# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\GUI.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_TSL_Control_Tool(object):
    def setupUi(self, TSL_Control_Tool):
        TSL_Control_Tool.setObjectName("TSL_Control_Tool")
        TSL_Control_Tool.resize(1200, 470)
        TSL_Control_Tool.setMinimumSize(QtCore.QSize(1200, 470))
        TSL_Control_Tool.setMaximumSize(QtCore.QSize(1200, 470))
        font = QtGui.QFont()
        font.setPointSize(12)
        TSL_Control_Tool.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("santec_logo_small.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        TSL_Control_Tool.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(TSL_Control_Tool)
        self.centralwidget.setMinimumSize(QtCore.QSize(1200, 470))
        self.centralwidget.setMaximumSize(QtCore.QSize(1200, 470))
        self.centralwidget.setObjectName("centralwidget")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(374, 14, 350, 441))
        self.frame_2.setMinimumSize(QtCore.QSize(350, 441))
        self.frame_2.setMaximumSize(QtCore.QSize(350, 16777215))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_2.setMidLineWidth(1)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.LD_tag_2 = QtWidgets.QLabel(self.frame_2)
        self.LD_tag_2.setMinimumSize(QtCore.QSize(60, 25))
        self.LD_tag_2.setMaximumSize(QtCore.QSize(60, 25))
        self.LD_tag_2.setObjectName("LD_tag_2")
        self.gridLayout_2.addWidget(self.LD_tag_2, 0, 0, 1, 1)
        self.LD_ON = QtWidgets.QPushButton(self.frame_2)
        self.LD_ON.setMinimumSize(QtCore.QSize(70, 25))
        self.LD_ON.setMaximumSize(QtCore.QSize(70, 25))
        self.LD_ON.setCheckable(True)
        self.LD_ON.setChecked(True)
        self.LD_ON.setObjectName("LD_ON")
        self.gridLayout_2.addWidget(self.LD_ON, 0, 1, 1, 2)
        self.LD_OFF = QtWidgets.QPushButton(self.frame_2)
        self.LD_OFF.setMinimumSize(QtCore.QSize(70, 25))
        self.LD_OFF.setMaximumSize(QtCore.QSize(70, 25))
        self.LD_OFF.setCheckable(True)
        self.LD_OFF.setChecked(False)
        self.LD_OFF.setObjectName("LD_OFF")
        self.gridLayout_2.addWidget(self.LD_OFF, 0, 3, 1, 1)
        self.pwr_tag_2 = QtWidgets.QLabel(self.frame_2)
        self.pwr_tag_2.setMinimumSize(QtCore.QSize(60, 25))
        self.pwr_tag_2.setMaximumSize(QtCore.QSize(60, 25))
        self.pwr_tag_2.setObjectName("pwr_tag_2")
        self.gridLayout_2.addWidget(self.pwr_tag_2, 1, 0, 1, 1)
        self.Pwr_auto = QtWidgets.QPushButton(self.frame_2)
        self.Pwr_auto.setMinimumSize(QtCore.QSize(70, 25))
        self.Pwr_auto.setMaximumSize(QtCore.QSize(70, 25))
        self.Pwr_auto.setAcceptDrops(False)
        self.Pwr_auto.setCheckable(True)
        self.Pwr_auto.setChecked(True)
        self.Pwr_auto.setDefault(False)
        self.Pwr_auto.setFlat(False)
        self.Pwr_auto.setObjectName("Pwr_auto")
        self.gridLayout_2.addWidget(self.Pwr_auto, 1, 1, 1, 2)
        self.Pwr_manual = QtWidgets.QPushButton(self.frame_2)
        self.Pwr_manual.setMinimumSize(QtCore.QSize(70, 25))
        self.Pwr_manual.setMaximumSize(QtCore.QSize(70, 25))
        self.Pwr_manual.setCheckable(True)
        self.Pwr_manual.setObjectName("Pwr_manual")
        self.gridLayout_2.addWidget(self.Pwr_manual, 1, 3, 1, 1)
        self.LD_tag_3 = QtWidgets.QLabel(self.frame_2)
        self.LD_tag_3.setMinimumSize(QtCore.QSize(60, 25))
        self.LD_tag_3.setMaximumSize(QtCore.QSize(60, 25))
        self.LD_tag_3.setObjectName("LD_tag_3")
        self.gridLayout_2.addWidget(self.LD_tag_3, 2, 0, 1, 1)
        self.shut_open = QtWidgets.QPushButton(self.frame_2)
        self.shut_open.setMinimumSize(QtCore.QSize(70, 25))
        self.shut_open.setMaximumSize(QtCore.QSize(70, 25))
        self.shut_open.setCheckable(True)
        self.shut_open.setChecked(True)
        self.shut_open.setObjectName("shut_open")
        self.gridLayout_2.addWidget(self.shut_open, 2, 1, 1, 2)
        self.shut_close = QtWidgets.QPushButton(self.frame_2)
        self.shut_close.setMinimumSize(QtCore.QSize(70, 25))
        self.shut_close.setMaximumSize(QtCore.QSize(70, 25))
        self.shut_close.setCheckable(True)
        self.shut_close.setObjectName("shut_close")
        self.gridLayout_2.addWidget(self.shut_close, 2, 3, 1, 1)
        self.lambda_tag = QtWidgets.QLabel(self.frame_2)
        self.lambda_tag.setMinimumSize(QtCore.QSize(125, 30))
        self.lambda_tag.setMaximumSize(QtCore.QSize(125, 30))
        self.lambda_tag.setObjectName("lambda_tag")
        self.gridLayout_2.addWidget(self.lambda_tag, 3, 0, 1, 2)
        self.lambda_input = QtWidgets.QLineEdit(self.frame_2)
        self.lambda_input.setMinimumSize(QtCore.QSize(120, 30))
        self.lambda_input.setMaximumSize(QtCore.QSize(120, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lambda_input.setFont(font)
        self.lambda_input.setObjectName("lambda_input")
        self.gridLayout_2.addWidget(self.lambda_input, 3, 2, 1, 2)
        self.lambda_go = QtWidgets.QPushButton(self.frame_2)
        self.lambda_go.setMinimumSize(QtCore.QSize(30, 30))
        self.lambda_go.setMaximumSize(QtCore.QSize(30, 30))
        self.lambda_go.setObjectName("lambda_go")
        self.gridLayout_2.addWidget(self.lambda_go, 3, 4, 1, 1)
        self.lambda_get = QtWidgets.QPushButton(self.frame_2)
        self.lambda_get.setMinimumSize(QtCore.QSize(125, 30))
        self.lambda_get.setMaximumSize(QtCore.QSize(125, 30))
        self.lambda_get.setObjectName("lambda_get")
        self.gridLayout_2.addWidget(self.lambda_get, 4, 0, 1, 2)
        self.lambda_disp = QtWidgets.QTextBrowser(self.frame_2)
        self.lambda_disp.setMinimumSize(QtCore.QSize(120, 30))
        self.lambda_disp.setMaximumSize(QtCore.QSize(120, 30))
        self.lambda_disp.setObjectName("lambda_disp")
        self.gridLayout_2.addWidget(self.lambda_disp, 4, 2, 1, 2)
        self.Pwr_tag = QtWidgets.QLabel(self.frame_2)
        self.Pwr_tag.setMinimumSize(QtCore.QSize(125, 30))
        self.Pwr_tag.setMaximumSize(QtCore.QSize(125, 30))
        self.Pwr_tag.setObjectName("Pwr_tag")
        self.gridLayout_2.addWidget(self.Pwr_tag, 5, 0, 1, 2)
        self.Pwr_input = QtWidgets.QLineEdit(self.frame_2)
        self.Pwr_input.setMinimumSize(QtCore.QSize(120, 30))
        self.Pwr_input.setMaximumSize(QtCore.QSize(120, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Pwr_input.setFont(font)
        self.Pwr_input.setDragEnabled(False)
        self.Pwr_input.setObjectName("Pwr_input")
        self.gridLayout_2.addWidget(self.Pwr_input, 5, 2, 1, 2)
        self.Pwr_go = QtWidgets.QPushButton(self.frame_2)
        self.Pwr_go.setMinimumSize(QtCore.QSize(30, 30))
        self.Pwr_go.setMaximumSize(QtCore.QSize(30, 30))
        self.Pwr_go.setObjectName("Pwr_go")
        self.gridLayout_2.addWidget(self.Pwr_go, 5, 4, 1, 1)
        self.Pwr_get = QtWidgets.QPushButton(self.frame_2)
        self.Pwr_get.setMinimumSize(QtCore.QSize(125, 30))
        self.Pwr_get.setMaximumSize(QtCore.QSize(125, 30))
        self.Pwr_get.setObjectName("Pwr_get")
        self.gridLayout_2.addWidget(self.Pwr_get, 6, 0, 1, 2)
        self.Pwr_disp = QtWidgets.QTextBrowser(self.frame_2)
        self.Pwr_disp.setMinimumSize(QtCore.QSize(120, 30))
        self.Pwr_disp.setMaximumSize(QtCore.QSize(120, 30))
        self.Pwr_disp.setObjectName("Pwr_disp")
        self.gridLayout_2.addWidget(self.Pwr_disp, 6, 2, 1, 2)
        self.Att_tag = QtWidgets.QLabel(self.frame_2)
        self.Att_tag.setMinimumSize(QtCore.QSize(125, 30))
        self.Att_tag.setMaximumSize(QtCore.QSize(125, 30))
        self.Att_tag.setObjectName("Att_tag")
        self.gridLayout_2.addWidget(self.Att_tag, 7, 0, 1, 2)
        self.Att_input = QtWidgets.QLineEdit(self.frame_2)
        self.Att_input.setMinimumSize(QtCore.QSize(120, 30))
        self.Att_input.setMaximumSize(QtCore.QSize(120, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Att_input.setFont(font)
        self.Att_input.setObjectName("Att_input")
        self.gridLayout_2.addWidget(self.Att_input, 7, 2, 1, 2)
        self.Att_go = QtWidgets.QPushButton(self.frame_2)
        self.Att_go.setMinimumSize(QtCore.QSize(30, 30))
        self.Att_go.setMaximumSize(QtCore.QSize(30, 30))
        self.Att_go.setObjectName("Att_go")
        self.gridLayout_2.addWidget(self.Att_go, 7, 4, 1, 1)
        self.Att_get = QtWidgets.QPushButton(self.frame_2)
        self.Att_get.setMinimumSize(QtCore.QSize(125, 30))
        self.Att_get.setMaximumSize(QtCore.QSize(125, 30))
        self.Att_get.setObjectName("Att_get")
        self.gridLayout_2.addWidget(self.Att_get, 8, 0, 1, 2)
        self.Att_disp = QtWidgets.QTextBrowser(self.frame_2)
        self.Att_disp.setMinimumSize(QtCore.QSize(120, 30))
        self.Att_disp.setMaximumSize(QtCore.QSize(120, 30))
        self.Att_disp.setObjectName("Att_disp")
        self.gridLayout_2.addWidget(self.Att_disp, 8, 2, 1, 2)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(18, 14, 350, 441))
        self.frame.setMinimumSize(QtCore.QSize(350, 441))
        self.frame.setMaximumSize(QtCore.QSize(350, 16777215))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setMidLineWidth(1)
        self.frame.setObjectName("frame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.Coh_Cont_tag = QtWidgets.QLabel(self.frame)
        self.Coh_Cont_tag.setMinimumSize(QtCore.QSize(60, 25))
        self.Coh_Cont_tag.setMaximumSize(QtCore.QSize(160, 25))
        self.Coh_Cont_tag.setObjectName("Coh_Cont_tag")
        self.gridLayout_3.addWidget(self.Coh_Cont_tag, 7, 0, 1, 1)
        self.Firmware_disp = QtWidgets.QTextBrowser(self.frame)
        self.Firmware_disp.setMinimumSize(QtCore.QSize(300, 30))
        self.Firmware_disp.setMaximumSize(QtCore.QSize(300, 30))
        self.Firmware_disp.setObjectName("Firmware_disp")
        self.gridLayout_3.addWidget(self.Firmware_disp, 5, 0, 1, 3)
        self.GPIB_DEL_tag = QtWidgets.QLabel(self.frame)
        self.GPIB_DEL_tag.setEnabled(True)
        self.GPIB_DEL_tag.setMinimumSize(QtCore.QSize(160, 30))
        self.GPIB_DEL_tag.setMaximumSize(QtCore.QSize(160, 30))
        self.GPIB_DEL_tag.setTextFormat(QtCore.Qt.AutoText)
        self.GPIB_DEL_tag.setObjectName("GPIB_DEL_tag")
        self.gridLayout_3.addWidget(self.GPIB_DEL_tag, 6, 0, 1, 1)
        self.Del_go = QtWidgets.QPushButton(self.frame)
        self.Del_go.setMinimumSize(QtCore.QSize(30, 30))
        self.Del_go.setMaximumSize(QtCore.QSize(30, 30))
        self.Del_go.setObjectName("Del_go")
        self.gridLayout_3.addWidget(self.Del_go, 6, 3, 1, 1)
        self.SN_disp = QtWidgets.QTextBrowser(self.frame)
        self.SN_disp.setMinimumSize(QtCore.QSize(300, 30))
        self.SN_disp.setMaximumSize(QtCore.QSize(300, 30))
        self.SN_disp.setObjectName("SN_disp")
        self.gridLayout_3.addWidget(self.SN_disp, 3, 0, 1, 3)
        self.CC_ON = QtWidgets.QPushButton(self.frame)
        self.CC_ON.setMinimumSize(QtCore.QSize(85, 25))
        self.CC_ON.setMaximumSize(QtCore.QSize(85, 25))
        self.CC_ON.setCheckable(True)
        self.CC_ON.setObjectName("CC_ON")
        self.gridLayout_3.addWidget(self.CC_ON, 7, 1, 1, 1)
        self.CC_OFF = QtWidgets.QPushButton(self.frame)
        self.CC_OFF.setMinimumSize(QtCore.QSize(85, 25))
        self.CC_OFF.setMaximumSize(QtCore.QSize(85, 25))
        self.CC_OFF.setCheckable(True)
        self.CC_OFF.setChecked(True)
        self.CC_OFF.setObjectName("CC_OFF")
        self.gridLayout_3.addWidget(self.CC_OFF, 7, 2, 1, 2)
        self.Amp_Mod_tag = QtWidgets.QLabel(self.frame)
        self.Amp_Mod_tag.setMinimumSize(QtCore.QSize(60, 25))
        self.Amp_Mod_tag.setMaximumSize(QtCore.QSize(160, 25))
        self.Amp_Mod_tag.setObjectName("Amp_Mod_tag")
        self.gridLayout_3.addWidget(self.Amp_Mod_tag, 8, 0, 1, 1)
        self.Amp_Mod_ON = QtWidgets.QPushButton(self.frame)
        self.Amp_Mod_ON.setMinimumSize(QtCore.QSize(85, 25))
        self.Amp_Mod_ON.setMaximumSize(QtCore.QSize(85, 25))
        self.Amp_Mod_ON.setCheckable(True)
        self.Amp_Mod_ON.setObjectName("Amp_Mod_ON")
        self.gridLayout_3.addWidget(self.Amp_Mod_ON, 8, 1, 1, 1)
        self.Amp_Mod_OFF = QtWidgets.QPushButton(self.frame)
        self.Amp_Mod_OFF.setMinimumSize(QtCore.QSize(85, 25))
        self.Amp_Mod_OFF.setMaximumSize(QtCore.QSize(85, 25))
        self.Amp_Mod_OFF.setCheckable(True)
        self.Amp_Mod_OFF.setChecked(True)
        self.Amp_Mod_OFF.setObjectName("Amp_Mod_OFF")
        self.gridLayout_3.addWidget(self.Amp_Mod_OFF, 8, 2, 1, 2)
        self.ProdName_disp = QtWidgets.QTextBrowser(self.frame)
        self.ProdName_disp.setMinimumSize(QtCore.QSize(300, 30))
        self.ProdName_disp.setMaximumSize(QtCore.QSize(300, 30))
        self.ProdName_disp.setObjectName("ProdName_disp")
        self.gridLayout_3.addWidget(self.ProdName_disp, 1, 0, 1, 3)
        self.GPIB_DEL_input = QtWidgets.QComboBox(self.frame)
        self.GPIB_DEL_input.setMinimumSize(QtCore.QSize(120, 30))
        self.GPIB_DEL_input.setMaximumSize(QtCore.QSize(141, 30))
        self.GPIB_DEL_input.setMaxVisibleItems(4)
        self.GPIB_DEL_input.setMaxCount(4)
        self.GPIB_DEL_input.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.GPIB_DEL_input.setFrame(False)
        self.GPIB_DEL_input.setObjectName("GPIB_DEL_input")
        self.GPIB_DEL_input.addItem("")
        self.GPIB_DEL_input.addItem("")
        self.GPIB_DEL_input.addItem("")
        self.GPIB_DEL_input.addItem("")
        self.gridLayout_3.addWidget(self.GPIB_DEL_input, 6, 1, 1, 2)
        self.SN_tag = QtWidgets.QLabel(self.frame)
        self.SN_tag.setMinimumSize(QtCore.QSize(130, 30))
        self.SN_tag.setMaximumSize(QtCore.QSize(130, 30))
        self.SN_tag.setObjectName("SN_tag")
        self.gridLayout_3.addWidget(self.SN_tag, 2, 0, 1, 1)
        self.Firmware_tag = QtWidgets.QLabel(self.frame)
        self.Firmware_tag.setMinimumSize(QtCore.QSize(130, 30))
        self.Firmware_tag.setMaximumSize(QtCore.QSize(130, 30))
        self.Firmware_tag.setObjectName("Firmware_tag")
        self.gridLayout_3.addWidget(self.Firmware_tag, 4, 0, 1, 1)
        self.TrigSrc_tag = QtWidgets.QLabel(self.frame)
        self.TrigSrc_tag.setMinimumSize(QtCore.QSize(160, 30))
        self.TrigSrc_tag.setMaximumSize(QtCore.QSize(160, 30))
        self.TrigSrc_tag.setTextFormat(QtCore.Qt.AutoText)
        self.TrigSrc_tag.setObjectName("TrigSrc_tag")
        self.gridLayout_3.addWidget(self.TrigSrc_tag, 9, 0, 1, 1)
        self.ProdName_tag = QtWidgets.QLabel(self.frame)
        self.ProdName_tag.setMinimumSize(QtCore.QSize(130, 30))
        self.ProdName_tag.setMaximumSize(QtCore.QSize(130, 30))
        self.ProdName_tag.setObjectName("ProdName_tag")
        self.gridLayout_3.addWidget(self.ProdName_tag, 0, 0, 1, 1)
        self.TrigMode_input = QtWidgets.QComboBox(self.frame)
        self.TrigMode_input.setMinimumSize(QtCore.QSize(120, 30))
        self.TrigMode_input.setMaximumSize(QtCore.QSize(141, 30))
        self.TrigMode_input.setMaxVisibleItems(4)
        self.TrigMode_input.setMaxCount(4)
        self.TrigMode_input.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.TrigMode_input.setFrame(False)
        self.TrigMode_input.setObjectName("TrigMode_input")
        self.TrigMode_input.addItem("")
        self.TrigMode_input.addItem("")
        self.TrigMode_input.addItem("")
        self.TrigMode_input.addItem("")
        self.gridLayout_3.addWidget(self.TrigMode_input, 10, 1, 1, 2)
        self.TrigSrc_go = QtWidgets.QPushButton(self.frame)
        self.TrigSrc_go.setMinimumSize(QtCore.QSize(30, 30))
        self.TrigSrc_go.setMaximumSize(QtCore.QSize(30, 30))
        self.TrigSrc_go.setObjectName("TrigSrc_go")
        self.gridLayout_3.addWidget(self.TrigSrc_go, 9, 3, 1, 1)
        self.TrigMode_go = QtWidgets.QPushButton(self.frame)
        self.TrigMode_go.setMinimumSize(QtCore.QSize(30, 30))
        self.TrigMode_go.setMaximumSize(QtCore.QSize(30, 30))
        self.TrigMode_go.setObjectName("TrigMode_go")
        self.gridLayout_3.addWidget(self.TrigMode_go, 10, 3, 1, 1)
        self.TrigSrc_input = QtWidgets.QComboBox(self.frame)
        self.TrigSrc_input.setMinimumSize(QtCore.QSize(120, 30))
        self.TrigSrc_input.setMaximumSize(QtCore.QSize(141, 30))
        self.TrigSrc_input.setMaxVisibleItems(2)
        self.TrigSrc_input.setMaxCount(2)
        self.TrigSrc_input.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.TrigSrc_input.setFrame(False)
        self.TrigSrc_input.setObjectName("TrigSrc_input")
        self.TrigSrc_input.addItem("")
        self.TrigSrc_input.addItem("")
        self.gridLayout_3.addWidget(self.TrigSrc_input, 9, 1, 1, 2)
        self.TrigMode_tag = QtWidgets.QLabel(self.frame)
        self.TrigMode_tag.setMinimumSize(QtCore.QSize(160, 30))
        self.TrigMode_tag.setMaximumSize(QtCore.QSize(160, 30))
        self.TrigMode_tag.setTextFormat(QtCore.Qt.AutoText)
        self.TrigMode_tag.setObjectName("TrigMode_tag")
        self.gridLayout_3.addWidget(self.TrigMode_tag, 10, 0, 1, 1)
        self.Connect = QtWidgets.QPushButton(self.frame)
        self.Connect.setMinimumSize(QtCore.QSize(85, 25))
        self.Connect.setMaximumSize(QtCore.QSize(85, 25))
        self.Connect.setCheckable(True)
        self.Connect.setChecked(True)
        self.Connect.setObjectName("Connect")
        self.gridLayout_3.addWidget(self.Connect, 0, 1, 1, 1)
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(730, 14, 453, 441))
        self.frame_3.setMinimumSize(QtCore.QSize(350, 361))
        self.frame_3.setMaximumSize(QtCore.QSize(453, 441))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_3.setMidLineWidth(1)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout.setObjectName("gridLayout")
        self.from_tag = QtWidgets.QLabel(self.frame_3)
        self.from_tag.setMinimumSize(QtCore.QSize(50, 30))
        self.from_tag.setMaximumSize(QtCore.QSize(50, 30))
        self.from_tag.setObjectName("from_tag")
        self.gridLayout.addWidget(self.from_tag, 2, 0, 1, 1)
        self.nm_tag = QtWidgets.QLabel(self.frame_3)
        self.nm_tag.setMinimumSize(QtCore.QSize(55, 30))
        self.nm_tag.setMaximumSize(QtCore.QSize(55, 30))
        self.nm_tag.setObjectName("nm_tag")
        self.gridLayout.addWidget(self.nm_tag, 2, 5, 1, 1)
        self.ScanSpeed_input = QtWidgets.QLineEdit(self.frame_3)
        self.ScanSpeed_input.setMinimumSize(QtCore.QSize(120, 30))
        self.ScanSpeed_input.setMaximumSize(QtCore.QSize(120, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ScanSpeed_input.setFont(font)
        self.ScanSpeed_input.setToolTip("")
        self.ScanSpeed_input.setObjectName("ScanSpeed_input")
        self.gridLayout.addWidget(self.ScanSpeed_input, 3, 4, 1, 1)
        self.lambdaEnd_input = QtWidgets.QLineEdit(self.frame_3)
        self.lambdaEnd_input.setMinimumSize(QtCore.QSize(120, 30))
        self.lambdaEnd_input.setMaximumSize(QtCore.QSize(120, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lambdaEnd_input.setFont(font)
        self.lambdaEnd_input.setObjectName("lambdaEnd_input")
        self.gridLayout.addWidget(self.lambdaEnd_input, 2, 4, 1, 1)
        self.ScanSpeed_tag = QtWidgets.QLabel(self.frame_3)
        self.ScanSpeed_tag.setMinimumSize(QtCore.QSize(80, 30))
        self.ScanSpeed_tag.setMaximumSize(QtCore.QSize(80, 30))
        self.ScanSpeed_tag.setObjectName("ScanSpeed_tag")
        self.gridLayout.addWidget(self.ScanSpeed_tag, 3, 0, 1, 2)
        self.Swp_mod_input = QtWidgets.QComboBox(self.frame_3)
        self.Swp_mod_input.setObjectName("Swp_mod_input")
        self.Swp_mod_input.addItem("")
        self.Swp_mod_input.addItem("")
        self.Swp_mod_input.addItem("")
        self.Swp_mod_input.addItem("")
        self.gridLayout.addWidget(self.Swp_mod_input, 1, 4, 1, 1)
        self.ScanParam_tag = QtWidgets.QLabel(self.frame_3)
        self.ScanParam_tag.setMinimumSize(QtCore.QSize(150, 30))
        self.ScanParam_tag.setMaximumSize(QtCore.QSize(150, 30))
        self.ScanParam_tag.setObjectName("ScanParam_tag")
        self.gridLayout.addWidget(self.ScanParam_tag, 0, 0, 1, 3)
        self.Swp_tag = QtWidgets.QLabel(self.frame_3)
        self.Swp_tag.setMinimumSize(QtCore.QSize(60, 25))
        self.Swp_tag.setMaximumSize(QtCore.QSize(120, 25))
        self.Swp_tag.setObjectName("Swp_tag")
        self.gridLayout.addWidget(self.Swp_tag, 1, 0, 1, 2)
        self.lambdaStart_input = QtWidgets.QLineEdit(self.frame_3)
        self.lambdaStart_input.setMinimumSize(QtCore.QSize(120, 30))
        self.lambdaStart_input.setMaximumSize(QtCore.QSize(120, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lambdaStart_input.setFont(font)
        self.lambdaStart_input.setObjectName("lambdaStart_input")
        self.gridLayout.addWidget(self.lambdaStart_input, 2, 1, 1, 2)
        self.nmto_tag = QtWidgets.QLabel(self.frame_3)
        self.nmto_tag.setMinimumSize(QtCore.QSize(55, 30))
        self.nmto_tag.setMaximumSize(QtCore.QSize(55, 30))
        self.nmto_tag.setObjectName("nmto_tag")
        self.gridLayout.addWidget(self.nmto_tag, 2, 3, 1, 1)
        self.sec_tag = QtWidgets.QLabel(self.frame_3)
        self.sec_tag.setMinimumSize(QtCore.QSize(55, 30))
        self.sec_tag.setMaximumSize(QtCore.QSize(55, 30))
        self.sec_tag.setObjectName("sec_tag")
        self.gridLayout.addWidget(self.sec_tag, 6, 5, 1, 1)
        self.Stop = QtWidgets.QPushButton(self.frame_3)
        self.Stop.setMinimumSize(QtCore.QSize(120, 30))
        self.Stop.setMaximumSize(QtCore.QSize(120, 30))
        self.Stop.setObjectName("Stop")
        self.gridLayout.addWidget(self.Stop, 8, 4, 1, 1)
        self.nms_tag = QtWidgets.QLabel(self.frame_3)
        self.nms_tag.setMinimumSize(QtCore.QSize(55, 30))
        self.nms_tag.setMaximumSize(QtCore.QSize(55, 30))
        self.nms_tag.setObjectName("nms_tag")
        self.gridLayout.addWidget(self.nms_tag, 3, 5, 1, 1)
        self.Dwell_tag = QtWidgets.QLabel(self.frame_3)
        self.Dwell_tag.setMinimumSize(QtCore.QSize(80, 30))
        self.Dwell_tag.setMaximumSize(QtCore.QSize(80, 30))
        self.Dwell_tag.setObjectName("Dwell_tag")
        self.gridLayout.addWidget(self.Dwell_tag, 6, 0, 1, 2)
        self.Start = QtWidgets.QPushButton(self.frame_3)
        self.Start.setMinimumSize(QtCore.QSize(120, 30))
        self.Start.setMaximumSize(QtCore.QSize(120, 30))
        self.Start.setCheckable(False)
        self.Start.setObjectName("Start")
        self.gridLayout.addWidget(self.Start, 8, 0, 1, 2)
        self.TriggStep_input = QtWidgets.QLineEdit(self.frame_3)
        self.TriggStep_input.setMinimumSize(QtCore.QSize(120, 30))
        self.TriggStep_input.setMaximumSize(QtCore.QSize(120, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.TriggStep_input.setFont(font)
        self.TriggStep_input.setToolTip("")
        self.TriggStep_input.setObjectName("TriggStep_input")
        self.gridLayout.addWidget(self.TriggStep_input, 4, 4, 1, 1)
        self.TriggStep_tag = QtWidgets.QLabel(self.frame_3)
        self.TriggStep_tag.setMinimumSize(QtCore.QSize(80, 30))
        self.TriggStep_tag.setMaximumSize(QtCore.QSize(120, 30))
        self.TriggStep_tag.setObjectName("TriggStep_tag")
        self.gridLayout.addWidget(self.TriggStep_tag, 4, 0, 1, 2)
        self.Repeat_tag = QtWidgets.QLabel(self.frame_3)
        self.Repeat_tag.setMinimumSize(QtCore.QSize(160, 30))
        self.Repeat_tag.setMaximumSize(QtCore.QSize(160, 30))
        self.Repeat_tag.setObjectName("Repeat_tag")
        self.gridLayout.addWidget(self.Repeat_tag, 7, 0, 1, 3)
        self.Repeat_input = QtWidgets.QLineEdit(self.frame_3)
        self.Repeat_input.setMinimumSize(QtCore.QSize(120, 30))
        self.Repeat_input.setMaximumSize(QtCore.QSize(120, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Repeat_input.setFont(font)
        self.Repeat_input.setObjectName("Repeat_input")
        self.gridLayout.addWidget(self.Repeat_input, 7, 4, 1, 1)
        self.nm_tag_3 = QtWidgets.QLabel(self.frame_3)
        self.nm_tag_3.setMinimumSize(QtCore.QSize(55, 30))
        self.nm_tag_3.setMaximumSize(QtCore.QSize(55, 30))
        self.nm_tag_3.setObjectName("nm_tag_3")
        self.gridLayout.addWidget(self.nm_tag_3, 4, 5, 1, 1)
        self.SoftTrig = QtWidgets.QPushButton(self.frame_3)
        self.SoftTrig.setMinimumSize(QtCore.QSize(120, 30))
        self.SoftTrig.setMaximumSize(QtCore.QSize(120, 30))
        self.SoftTrig.setObjectName("SoftTrig")
        self.gridLayout.addWidget(self.SoftTrig, 8, 2, 1, 2)
        self.nm_tag_2 = QtWidgets.QLabel(self.frame_3)
        self.nm_tag_2.setMinimumSize(QtCore.QSize(55, 30))
        self.nm_tag_2.setMaximumSize(QtCore.QSize(55, 30))
        self.nm_tag_2.setObjectName("nm_tag_2")
        self.gridLayout.addWidget(self.nm_tag_2, 5, 5, 1, 1)
        self.Cycle_tag = QtWidgets.QLabel(self.frame_3)
        self.Cycle_tag.setMinimumSize(QtCore.QSize(55, 30))
        self.Cycle_tag.setMaximumSize(QtCore.QSize(55, 30))
        self.Cycle_tag.setObjectName("Cycle_tag")
        self.gridLayout.addWidget(self.Cycle_tag, 7, 5, 1, 1)
        self.Dwell_input = QtWidgets.QLineEdit(self.frame_3)
        self.Dwell_input.setMinimumSize(QtCore.QSize(120, 30))
        self.Dwell_input.setMaximumSize(QtCore.QSize(120, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Dwell_input.setFont(font)
        self.Dwell_input.setObjectName("Dwell_input")
        self.gridLayout.addWidget(self.Dwell_input, 6, 4, 1, 1)
        self.Step_input = QtWidgets.QLineEdit(self.frame_3)
        self.Step_input.setMinimumSize(QtCore.QSize(120, 30))
        self.Step_input.setMaximumSize(QtCore.QSize(120, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Step_input.setFont(font)
        self.Step_input.setObjectName("Step_input")
        self.gridLayout.addWidget(self.Step_input, 5, 4, 1, 1)
        self.Step_tag = QtWidgets.QLabel(self.frame_3)
        self.Step_tag.setMinimumSize(QtCore.QSize(80, 30))
        self.Step_tag.setMaximumSize(QtCore.QSize(80, 30))
        self.Step_tag.setObjectName("Step_tag")
        self.gridLayout.addWidget(self.Step_tag, 5, 0, 1, 2)
        self.Swp_mode_go = QtWidgets.QPushButton(self.frame_3)
        self.Swp_mode_go.setMinimumSize(QtCore.QSize(30, 30))
        self.Swp_mode_go.setMaximumSize(QtCore.QSize(30, 30))
        self.Swp_mode_go.setObjectName("Swp_mode_go")
        self.gridLayout.addWidget(self.Swp_mode_go, 1, 5, 1, 1)
        self.frame_4 = QtWidgets.QFrame(self.centralwidget)
        self.frame_4.setGeometry(QtCore.QRect(741, 260, 421, 80))
        self.frame_4.setAutoFillBackground(True)
        self.frame_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.frame_5 = QtWidgets.QFrame(self.centralwidget)
        self.frame_5.setGeometry(QtCore.QRect(741, 170, 421, 80))
        self.frame_5.setAutoFillBackground(True)
        self.frame_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        TSL_Control_Tool.setCentralWidget(self.centralwidget)

        self.retranslateUi(TSL_Control_Tool)
        self.GPIB_DEL_input.setCurrentIndex(2)
        self.TrigMode_input.setCurrentIndex(3)
        self.TrigSrc_input.setCurrentIndex(0)
        self.Swp_mod_input.setCurrentIndex(1)
        self.LD_ON.clicked.connect(self.LD_OFF.toggle)
        self.LD_OFF.clicked.connect(self.LD_ON.toggle)
        self.Pwr_auto.clicked.connect(self.Pwr_manual.toggle)
        self.Pwr_auto.clicked.connect(self.Pwr_input.show)
        self.Pwr_auto.clicked.connect(self.Pwr_go.show)
        self.Pwr_auto.clicked.connect(self.Att_input.hide)
        self.Pwr_auto.clicked.connect(self.Att_go.hide)
        self.Pwr_manual.clicked.connect(self.Pwr_auto.toggle)
        self.Pwr_manual.clicked.connect(self.Pwr_input.hide)
        self.Pwr_manual.clicked.connect(self.Pwr_go.hide)
        self.Pwr_manual.clicked.connect(self.Att_input.show)
        self.Pwr_manual.clicked.connect(self.Att_go.show)
        self.CC_ON.clicked.connect(self.CC_OFF.toggle)
        self.CC_OFF.clicked.connect(self.CC_ON.toggle)
        self.Amp_Mod_ON.clicked.connect(self.Amp_Mod_OFF.toggle)
        self.Amp_Mod_OFF.clicked.connect(self.Amp_Mod_ON.toggle)
        self.shut_open.clicked.connect(self.shut_close.toggle)
        self.shut_close.clicked.connect(self.shut_open.toggle)
        QtCore.QMetaObject.connectSlotsByName(TSL_Control_Tool)
        TSL_Control_Tool.setTabOrder(self.ProdName_disp, self.SN_disp)
        TSL_Control_Tool.setTabOrder(self.SN_disp, self.Firmware_disp)
        TSL_Control_Tool.setTabOrder(self.Firmware_disp, self.GPIB_DEL_input)
        TSL_Control_Tool.setTabOrder(self.GPIB_DEL_input, self.Del_go)
        TSL_Control_Tool.setTabOrder(self.Del_go, self.CC_ON)
        TSL_Control_Tool.setTabOrder(self.CC_ON, self.CC_OFF)
        TSL_Control_Tool.setTabOrder(self.CC_OFF, self.Amp_Mod_ON)
        TSL_Control_Tool.setTabOrder(self.Amp_Mod_ON, self.Amp_Mod_OFF)
        TSL_Control_Tool.setTabOrder(self.Amp_Mod_OFF, self.TrigSrc_input)
        TSL_Control_Tool.setTabOrder(self.TrigSrc_input, self.TrigSrc_go)
        TSL_Control_Tool.setTabOrder(self.TrigSrc_go, self.TrigMode_input)
        TSL_Control_Tool.setTabOrder(self.TrigMode_input, self.TrigMode_go)
        TSL_Control_Tool.setTabOrder(self.TrigMode_go, self.LD_ON)
        TSL_Control_Tool.setTabOrder(self.LD_ON, self.LD_OFF)
        TSL_Control_Tool.setTabOrder(self.LD_OFF, self.Pwr_auto)
        TSL_Control_Tool.setTabOrder(self.Pwr_auto, self.Pwr_manual)
        TSL_Control_Tool.setTabOrder(self.Pwr_manual, self.shut_open)
        TSL_Control_Tool.setTabOrder(self.shut_open, self.shut_close)
        TSL_Control_Tool.setTabOrder(self.shut_close, self.lambda_input)
        TSL_Control_Tool.setTabOrder(self.lambda_input, self.lambda_go)
        TSL_Control_Tool.setTabOrder(self.lambda_go, self.lambda_get)
        TSL_Control_Tool.setTabOrder(self.lambda_get, self.lambda_disp)
        TSL_Control_Tool.setTabOrder(self.lambda_disp, self.Pwr_input)
        TSL_Control_Tool.setTabOrder(self.Pwr_input, self.Pwr_go)
        TSL_Control_Tool.setTabOrder(self.Pwr_go, self.Pwr_get)
        TSL_Control_Tool.setTabOrder(self.Pwr_get, self.Pwr_disp)
        TSL_Control_Tool.setTabOrder(self.Pwr_disp, self.Att_input)
        TSL_Control_Tool.setTabOrder(self.Att_input, self.Att_go)
        TSL_Control_Tool.setTabOrder(self.Att_go, self.Att_get)
        TSL_Control_Tool.setTabOrder(self.Att_get, self.Att_disp)
        TSL_Control_Tool.setTabOrder(self.Att_disp, self.Swp_mod_input)
        TSL_Control_Tool.setTabOrder(self.Swp_mod_input, self.Swp_mode_go)
        TSL_Control_Tool.setTabOrder(self.Swp_mode_go, self.lambdaStart_input)
        TSL_Control_Tool.setTabOrder(self.lambdaStart_input, self.lambdaEnd_input)
        TSL_Control_Tool.setTabOrder(self.lambdaEnd_input, self.ScanSpeed_input)
        TSL_Control_Tool.setTabOrder(self.ScanSpeed_input, self.TriggStep_input)
        TSL_Control_Tool.setTabOrder(self.TriggStep_input, self.Step_input)
        TSL_Control_Tool.setTabOrder(self.Step_input, self.Dwell_input)
        TSL_Control_Tool.setTabOrder(self.Dwell_input, self.Repeat_input)
        TSL_Control_Tool.setTabOrder(self.Repeat_input, self.Start)
        TSL_Control_Tool.setTabOrder(self.Start, self.SoftTrig)
        TSL_Control_Tool.setTabOrder(self.SoftTrig, self.Stop)

    def retranslateUi(self, TSL_Control_Tool):
        _translate = QtCore.QCoreApplication.translate
        TSL_Control_Tool.setWindowTitle(_translate("TSL_Control_Tool", "TSL Control Software"))
        self.LD_tag_2.setText(_translate("TSL_Control_Tool", "LD"))
        self.LD_ON.setText(_translate("TSL_Control_Tool", "ON"))
        self.LD_OFF.setText(_translate("TSL_Control_Tool", "OFF"))
        self.pwr_tag_2.setText(_translate("TSL_Control_Tool", "Power"))
        self.Pwr_auto.setText(_translate("TSL_Control_Tool", "AUTO"))
        self.Pwr_manual.setText(_translate("TSL_Control_Tool", "MAN"))
        self.LD_tag_3.setText(_translate("TSL_Control_Tool", "Shutter"))
        self.shut_open.setText(_translate("TSL_Control_Tool", "OPEN"))
        self.shut_close.setText(_translate("TSL_Control_Tool", "CLOSE"))
        self.lambda_tag.setText(_translate("TSL_Control_Tool", "Wavelength (nm)"))
        self.lambda_go.setText(_translate("TSL_Control_Tool", "GO"))
        self.lambda_get.setText(_translate("TSL_Control_Tool", "Get"))
        self.lambda_disp.setHtml(_translate("TSL_Control_Tool", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.Pwr_tag.setText(_translate("TSL_Control_Tool", "Power (dBm)"))
        self.Pwr_go.setText(_translate("TSL_Control_Tool", "GO"))
        self.Pwr_get.setText(_translate("TSL_Control_Tool", "Get"))
        self.Pwr_disp.setHtml(_translate("TSL_Control_Tool", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.Att_tag.setText(_translate("TSL_Control_Tool", "Attenuator (dB)"))
        self.Att_go.setText(_translate("TSL_Control_Tool", "GO"))
        self.Att_get.setText(_translate("TSL_Control_Tool", "Get"))
        self.Att_disp.setHtml(_translate("TSL_Control_Tool", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.Coh_Cont_tag.setText(_translate("TSL_Control_Tool", "Coherence Control"))
        self.GPIB_DEL_tag.setText(_translate("TSL_Control_Tool", "GPIB delimiter"))
        self.Del_go.setText(_translate("TSL_Control_Tool", "GO"))
        self.CC_ON.setText(_translate("TSL_Control_Tool", "ON"))
        self.CC_OFF.setText(_translate("TSL_Control_Tool", "OFF"))
        self.Amp_Mod_tag.setText(_translate("TSL_Control_Tool", "Amp. Modulation"))
        self.Amp_Mod_ON.setText(_translate("TSL_Control_Tool", "ON"))
        self.Amp_Mod_OFF.setText(_translate("TSL_Control_Tool", "OFF"))
        self.ProdName_disp.setHtml(_translate("TSL_Control_Tool", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.GPIB_DEL_input.setItemText(0, _translate("TSL_Control_Tool", "CR"))
        self.GPIB_DEL_input.setItemText(1, _translate("TSL_Control_Tool", "LF"))
        self.GPIB_DEL_input.setItemText(2, _translate("TSL_Control_Tool", "CR+LF"))
        self.GPIB_DEL_input.setItemText(3, _translate("TSL_Control_Tool", "EOI"))
        self.SN_tag.setText(_translate("TSL_Control_Tool", "Serial number"))
        self.Firmware_tag.setText(_translate("TSL_Control_Tool", "Firmware version"))
        self.TrigSrc_tag.setText(_translate("TSL_Control_Tool", "Input Trigger Source"))
        self.ProdName_tag.setText(_translate("TSL_Control_Tool", "Product name"))
        self.TrigMode_input.setItemText(0, _translate("TSL_Control_Tool", " None"))
        self.TrigMode_input.setItemText(1, _translate("TSL_Control_Tool", " Stop"))
        self.TrigMode_input.setItemText(2, _translate("TSL_Control_Tool", " Start"))
        self.TrigMode_input.setItemText(3, _translate("TSL_Control_Tool", " Step"))
        self.TrigSrc_go.setText(_translate("TSL_Control_Tool", "GO"))
        self.TrigMode_go.setText(_translate("TSL_Control_Tool", "GO"))
        self.TrigSrc_input.setItemText(0, _translate("TSL_Control_Tool", " FRONT KEY"))
        self.TrigSrc_input.setItemText(1, _translate("TSL_Control_Tool", " REAR BNC"))
        self.TrigMode_tag.setText(_translate("TSL_Control_Tool", "Output Trigger Mode"))
        self.Connect.setText(_translate("TSL_Control_Tool", "Connect"))
        self.from_tag.setText(_translate("TSL_Control_Tool", "From"))
        self.nm_tag.setText(_translate("TSL_Control_Tool", "nm"))
        self.ScanSpeed_tag.setToolTip(_translate("TSL_Control_Tool", "<html><head/><body><p>1~100nm/sec</p></body></html>"))
        self.ScanSpeed_tag.setText(_translate("TSL_Control_Tool", "Scan speed"))
        self.Swp_mod_input.setItemText(0, _translate("TSL_Control_Tool", "Step →"))
        self.Swp_mod_input.setItemText(1, _translate("TSL_Control_Tool", "Cont →"))
        self.Swp_mod_input.setItemText(2, _translate("TSL_Control_Tool", "Step ↔"))
        self.Swp_mod_input.setItemText(3, _translate("TSL_Control_Tool", "Cont ↔"))
        self.ScanParam_tag.setText(_translate("TSL_Control_Tool", "Scanning parameters"))
        self.Swp_tag.setText(_translate("TSL_Control_Tool", "Sweep mode"))
        self.nmto_tag.setText(_translate("TSL_Control_Tool", "nm, To"))
        self.sec_tag.setText(_translate("TSL_Control_Tool", "sec"))
        self.Stop.setText(_translate("TSL_Control_Tool", "Stop"))
        self.nms_tag.setText(_translate("TSL_Control_Tool", "nm/s"))
        self.Dwell_tag.setText(_translate("TSL_Control_Tool", "Dwell time"))
        self.Start.setText(_translate("TSL_Control_Tool", "Start"))
        self.TriggStep_tag.setText(_translate("TSL_Control_Tool", "Trigger Step"))
        self.Repeat_tag.setText(_translate("TSL_Control_Tool", "Repeat Cycles"))
        self.nm_tag_3.setText(_translate("TSL_Control_Tool", "nm"))
        self.SoftTrig.setText(_translate("TSL_Control_Tool", "Soft Trigger"))
        self.nm_tag_2.setText(_translate("TSL_Control_Tool", "nm"))
        self.Cycle_tag.setText(_translate("TSL_Control_Tool", "Cycles"))
        self.Step_tag.setText(_translate("TSL_Control_Tool", "Step"))
        self.Swp_mode_go.setText(_translate("TSL_Control_Tool", "GO"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TSL_Control_Tool = QtWidgets.QMainWindow()
    ui = Ui_TSL_Control_Tool()
    ui.setupUi(TSL_Control_Tool)
    TSL_Control_Tool.show()
    sys.exit(app.exec_())

